// TODO: 多言語対応（ソース全体）

const ARTIFACT_SET = {
    Adventurer: {
        name: "冒険者",
        set2: new Bonus("hp", 1000), // TODO: hp_buf が係るのか検証
        set4: null,
    },
    LuckyDog: {
        name: "幸運",
        set2: new Bonus("def", 100),
        set4: null,
    },
    // Doctor: { name: "医者" },
    Instructor: {
        name: "教官",
        set2: new Bonus("elem", 80),
        set4: new Bonus("elem", 120, "元素反応後", 8, 0, "all"),
    },
    Berserker: {
        name: "狂戦士",
        set2: new Bonus("cri_rate", 12),
        set4: new Bonus("cri_rate", 24, "HP70%以下の時"),
    },
    TheExile: {
        name: "亡命者",
        set2: new Bonus("en_rec", 20),
        set4: null,
    },
    Sojourner: {
        name: "旅人の心",
        set2: new Bonus("atk_buf", 18),
        set4: new Bonus("heavy_cri", 30),
    },
    Artist: {
        name: "武人",
        set2: new Bonus(["normal_dmg", "heavy_dmg"], 15),
        set4: new Bonus(["normal_dmg", "heavy_dmg"], 25, "元素スキル発動後", 8),
    },
    Defender: {
        name: "守護の心",
        set2: new Bonus("def_buf", 30),
        set4: null,
    },
    // Miracle: { name: "奇跡" },
    BraveHeart: {
        name: "勇士の心",
        set2: new Bonus("atk_buf", 18),
        set4: new Bonus("any_dmg", 30, "HP50%以上の敵"),
    },
    Gambler: {
        name: "博徒",
        set2: new Bonus("skill_dmg", 20),
        set4: null,
    },
    Scholar: {
        name: "学者",
        set2: new Bonus("en_rec", 20),
        set4: null,
    },
    Gladiator: {
        name: "剣闘士のフィナーレ",
        set2: new Bonus("atk_buf", 18),
        set4: new Bonus("normal_dmg", 35, "片手剣、両手剣、長柄武器キャラの時"),
    },
    // Maiden: { name: "愛される少女" },
    Noblesse: {
        name: "旧貴族のしつけ",
        set2: new Bonus("burst_dmg", 20),
        set4: new Bonus("atk_buf", 20, "元素爆発後", 12, "all"),
    },
    Chivalry: {
        name: "血染めの騎士道",
        set2: new Bonus("phys_dmg", 25),
        set4: new Bonus("heavy_dmg", 50, "敵を倒した後", 10),
    },
    Troupe: {
        name: "大地を流浪する楽団",
        set2: new Bonus("elem", 80),
        set4: new Bonus("heavy_dmg", 35, "弓、法器キャラの時"),
    },
    Venerer: {
        name: "翆緑の影",
        set2: new Bonus("anemo_dmg", 15),
        set4: new Bonus("swirl_dmg", 60), // 耐性-40%付き
    },
    Fury: {
        name: "雷のような怒り",
        set2: new Bonus("elect_dmg", 15),
        set4: new Bonus(["ovrload_dmg", "echarge_dmg", "conduct_dmg"], 40),
    },
    Thundersoother: {
        name: "雷を鎮める尊者",
        set2: null,
        set4: new Bonus("any_dmg", 35, "雷元素の影響を受けた敵"),
    },
    CrimsonWitch: {
        name: "燃え盛る炎の魔女",
        set2: new Bonus("pyro_dmg", 15),
        set4: [
            new Bonus("overload_dmg", 40),
            new Bonus(["vaporize_dmg", "melt_dmg"], 15),
            new Bonus("overload_dmg", 12.5, "元素スキル発動後", 10, 3),
            new Bonus(["vaporize_dmg", "melt_dmg"], 7.5, "元素スキル発動後", 10, 3),
        ],
    },
    Lavawalker: {
        name: "烈火を渡る尊者",
        set2: null,
        set4: new Bonus("any_dmg", 35, "炎元素の影響を受けた敵"),
    },
    Petra: {
        name: "悠久の磐岩",
        set2: new Bonus("geo_dmg", 15),
        set4: new Bonus("elem_dmg", 35, "結晶反応した元素", 10, 0, "all"),
    },
    Bolide: {
        name: "逆飛びの流星",
        set2: null,
        set4: new Bonus(["normal_dmg", "heavy_dmg"], 40, "シールド状態の時"),
    },
};

const FLOWER_LIST = {
    other: "-",
    Adventurer: "冒険者の花",
    LuckyDog: "幸運のクローバー",
    Doctor: "医者のアネモネ",
    Instructor: "教官の花飾り",
    Berserker: "狂戦士の薔薇",
    TheExile: "亡命者の花",
    Sojourner: "故人の心",
    Artist: "武人の赤い花",
    Defender: "守護の花",
    Miracle: "奇跡の花",
    BraveHeart: "勇士の勲章",
    Gambler: "博徒の花飾り",
    Scholar: "学者のしおり",
    Gladiator: "剣闘士の未練",
    Maiden: "彼方にある少女の心",
    Noblesse: "旧貴族の花",
    Chivalry: "血染めの鉄の心",
    Troupe: "楽団の朝の光",
    Venerer: "野花の記憶の草原",
    Fury: "雷鳴の憐み",
    Thundersoother: "雷討ちの心",
    CrimsonWitch: "魔女の炎の花",
    Lavawalker: "火渡りの堅実",
    Petra: "盤石芽生の花",
    Bolide: "夏祭りの花",
};

const FEATHER_LIST = {
    other: "-",
    Adventurer: "冒険者の羽根",
    LuckyDog: "幸運の鷹の羽根",
    Doctor: "医者の梟の羽根",
    Instructor: "教官の羽飾り",
    Berserker: "狂戦士の羽根",
    TheExile: "亡命者の羽根",
    Sojourner: "帰郷の羽",
    Artist: "武人の羽飾り",
    Defender: "守護の印",
    Miracle: "奇跡の羽根",
    BraveHeart: "勇士の期待",
    Gambler: "博徒の羽飾り",
    Scholar: "学者の羽根ペン",
    Gladiator: "剣闘士の帰着",
    Maiden: "少女の揺らぐ思い",
    Noblesse: "旧貴族の羽根",
    Chivalry: "血染めの黒羽",
    Troupe: "琴師の矢羽",
    Venerer: "狩人の青緑色の矢羽",
    Fury: "雷災の生存者",
    Thundersoother: "雷討ちの羽根",
    CrimsonWitch: "魔女の炎の羽根",
    Lavawalker: "火渡りの解放",
    Petra: "嵯峨連山の翼",
    Bolide: "夏祭りの終わり",
};

const SANDS_LIST = {
    other: "-",
    Adventurer: "冒険者の懐中時計",
    LuckyDog: "幸運の砂時計",
    Doctor: "医者の懐中時計",
    Instructor: "教官の懐中時計",
    Berserker: "狂戦士の時計",
    TheExile: "亡命者の懐中時計",
    Sojourner: "逐光の石",
    Artist: "武人の水時計",
    Defender: "守護の置き時計",
    Miracle: "奇跡の砂",
    BraveHeart: "勇士の毅然",
    Gambler: "博徒の懐中時計",
    Scholar: "学者の時計",
    Gladiator: "剣闘士の希望",
    Maiden: "少女の短い華年",
    Noblesse: "旧貴族の時計",
    Chivalry: "騎士が血に染めた時",
    Troupe: "フィナーレの時計",
    Venerer: "緑の狩人の決心",
    Fury: "雷霆の時計",
    Thundersoother: "雷討ちの刻",
    CrimsonWitch: "魔女の破滅の時",
    Lavawalker: "火渡りの苦しみ",
    Petra: "星羅圭玉の日時計",
    Bolide: "夏祭りの刻",
};

const GOBLET_LIST = {
    other: "-",
    Adventurer: "冒険者の金杯",
    LuckyDog: "幸運のコップ",
    Doctor: "医者の薬壺",
    Instructor: "教官のティーカップ",
    Berserker: "狂戦士のコップ",
    TheExile: "亡命者のコップ",
    Sojourner: "異国の杯",
    Artist: "武人の酒器",
    Defender: "守護の瓶",
    Miracle: "奇跡のコップ",
    BraveHeart: "勇士の壮行",
    Gambler: "博徒のツボ",
    Scholar: "学者のコップ",
    Gladiator: "剣闘士の酩酊",
    Maiden: "少女の暫く息抜き",
    Noblesse: "旧貴族の銀瓶",
    Chivalry: "血染めの騎士のコップ",
    Troupe: "吟遊者の水筒",
    Venerer: "緑の狩人の容器",
    Fury: "落雷の前兆",
    Thundersoother: "雷討ちの器",
    CrimsonWitch: "魔女の心の炎",
    Lavawalker: "火渡りの悟り",
    Petra: "危岩盤石の杯",
    Bolide: "夏祭りの水風船",
};

const CIRCLET_LIST = {
    other: "-",
    Adventurer: "冒険者のバンダナ",
    LuckyDog: "幸運の冠",
    Doctor: "医者の方巾",
    Instructor: "教官の帽子",
    Berserker: "狂戦士の仮面",
    TheExile: "亡命者の冠",
    Sojourner: "別離の冠",
    Artist: "武人のバンダナ",
    Defender: "守護の帯",
    Miracle: "奇跡のピアス",
    BraveHeart: "勇士の冠",
    Gambler: "博徒のピアス",
    Scholar: "学者のレンズ",
    Gladiator: "剣闘士の凱旋",
    Maiden: "少女の儚き顔",
    Noblesse: "旧貴族の仮面",
    Chivalry: "血染めの鉄仮面",
    Troupe: "指揮者のハット",
    Venerer: "緑の狩人の冠",
    Fury: "雷を呼ぶ冠",
    Thundersoother: "雷討ちの冠",
    CrimsonWitch: "焦げた魔女の帽子",
    Lavawalker: "火渡りの知恵",
    Petra: "不動玄石の相",
    Bolide: "夏祭りの仮面",
};