"use strict";
const SWORD_LIST = {
    other: {
        name: "-",
        star: 1,
        second: StatusBonusType.Other,
    },
    AquilaFavonia: {
        name: "風鷹剣",
        star: 5,
        atk: WEAPON_ATK5[48],
        second: ElementBonusType.Phys,
        secval: WEAPON_SUB5.phys_dmg,
        passive: { items: StatusBonusType.AtkBuf, value: [20, 25, 30, 35, 40] },
    },
    SkywardBlade: {
        name: "天空の刃",
        star: 5,
        atk: WEAPON_ATK5[46],
        second: StatusBonusType.EnRec,
        secval: WEAPON_SUB5.en_rec,
        passive: { items: CriticalBonusType.Rate, value: [4, 5, 6, 7, 8] },
    },
    SummitShaper: {
        name: "斬山の刃",
        star: 5,
        atk: WEAPON_ATK5[46],
        second: StatusBonusType.AtkBuf,
        secval: WEAPON_SUB5.atk_buf,
        passive: [
            { items: StatusBonusType.AtkBuf, value: [4, 5, 6, 7, 8], limit: "攻撃が命中した時", times: 8, stack: 5 },
            { items: StatusBonusType.AtkBuf, value: [4, 5, 6, 7, 8], limit: "さらにシールド状態の時", times: 8, stack: 5 },
        ]
    },
    PrimordialJadeCutter: {
        name: "磐岩結緑",
        star: 5,
        atk: WEAPON_ATK5[44],
        second: CriticalBonusType.Rate,
        secval: WEAPON_SUB5.cri_rate,
        passive: [
            { items: StatusBonusType.HpBuf, value: [20, 25, 30, 35, 40] },
            { extra: ExtraBonusType.Flat, dest: FlatBonusDest.Atk, base: FlatBonusBase.Hp, value: [1.2, 1.5, 1.8, 2.1, 2.4] },
        ]
    },
    FavoniusSword: {
        name: "西風剣",
        star: 4,
        atk: WEAPON_ATK4[41],
        second: StatusBonusType.EnRec,
        secval: WEAPON_SUB4.en_rec,
    },
    SacrificialSword: {
        name: "祭礼の剣",
        star: 4,
        atk: WEAPON_ATK4[41],
        second: StatusBonusType.EnRec,
        secval: WEAPON_SUB4.en_rec,
    },
    LionsRoar: {
        name: "匣中龍吟",
        star: 4,
        atk: WEAPON_ATK4[42],
        second: StatusBonusType.AtkBuf,
        secval: WEAPON_SUB4.atk_buf,
        passive: { items: StatusBonusType.AnyDmg, value: [20, 24, 28, 32, 36], limit: "炎、雷元素の影響を受けた敵" },
    },
    TheFlute: {
        name: "笛の剣",
        star: 4,
        atk: WEAPON_ATK4[42],
        second: StatusBonusType.AtkBuf,
        secval: WEAPON_SUB4.atk_buf,
    },
    AlleyFlash: {
        name: "ダークアレイの閃光",
        star: 4,
        atk: WEAPON_ATK4[45],
        second: StatusBonusType.Elem,
        secval: [12, 21, 31, 36, 41, 45, 50, 55],
        passive: { items: StatusBonusType.AnyDmg, value: [12, 15, 18, 21, 24] },
    },
    RoyalLongsword: {
        name: "旧貴族長剣",
        star: 4,
        atk: WEAPON_ATK4[42],
        second: StatusBonusType.AtkBuf,
        secval: WEAPON_SUB4.atk_buf,
        passive: { items: CriticalBonusType.Rate, value: [8, 10, 12, 14, 16], limit: "ダメージを与えた時", stack: 5 },
    },
    BlackcliffLongsword: {
        name: "黒岩の長剣",
        star: 4,
        atk: WEAPON_ATK4[44],
        second: CriticalBonusType.Damage,
        secval: [8.0, 14.1, 20.6, 23.8, 27.1, 30.3, 33.5, 36.8],
        passive: { items: StatusBonusType.AtkBuf, value: [12, 15, 18, 21, 24], limit: "敵を倒した後", times: 30, stack: 3 },
    },
    PrototypeRancour: {
        name: "斬岩・試作",
        star: 4,
        atk: WEAPON_ATK4[44],
        second: ElementBonusType.Phys,
        secval: WEAPON_SUB4.phys_dmg,
        passive: { items: [StatusBonusType.AtkBuf, StatusBonusType.DefBuf], value: [4, 5, 6, 7, 8], limit: "通常攻撃または重撃が命中した時", times: 6, stack: 4 },
    },
    IronSting: {
        name: "鉄蜂の刺し",
        star: 4,
        atk: WEAPON_ATK4[42],
        second: StatusBonusType.Elem,
        secval: WEAPON_SUB4.elem,
        passive: { items: StatusBonusType.AnyDmg, value: [6, 7.5, 9, 10.5, 12], limit: "元素ダメージを与えた後", times: 6, stack: 2 },
    },
    SwordDescension: {
        name: "降臨の剣",
        star: 4,
        atk: WEAPON_ATK4[39],
        second: StatusBonusType.AtkBuf,
        secval: WEAPON_SUB3.atk_buf,
        passive: { items: StatusBonusType.Atk, value: [66, 66, 66, 66, 66], limit: "旅人が装備した時" },
    },
    BlackSword: {
        name: "黒剣",
        star: 4,
        atk: WEAPON_ATK4[42],
        second: CriticalBonusType.Rate,
        secval: WEAPON_SUB4.cri_rate,
        passive: { items: [CombatBonusType.Normal, CombatBonusType.Heavy], value: [20, 25, 30, 35, 40] },
    },
    FesteringDesire: {
        name: "腐植の剣",
        star: 4,
        atk: WEAPON_ATK4[42],
        second: StatusBonusType.EnRec,
        secval: [10.0, 17.7, 25.8, 29.8, 33.8, 37.9, 41.9, 45.9],
        passive: [
            { items: CombatBonusType.Skill, value: [16, 20, 24, 28, 32] },
            { items: CriticalBonusType.Skill, value: [6, 7.5, 9, 10.5, 12] },
        ]
    },
    SkyriderSword: {
        name: "飛天御剣",
        star: 3,
        atk: WEAPON_ATK3[38],
        second: StatusBonusType.EnRec,
        secval: WEAPON_SUB3.en_rec,
        passive: { items: StatusBonusType.AtkBuf, value: [12, 15, 18, 21, 25], limit: "元素爆発後", times: 15 },
    },
    FilletBlade: {
        name: "チ虎魚の刀",
        star: 3,
        atk: WEAPON_ATK3[39],
        second: StatusBonusType.AtkBuf,
        secval: WEAPON_SUB3.atk_buf,
    },
    TravelersSword: {
        name: "旅道の剣",
        star: 3,
        atk: WEAPON_ATK3[40],
        second: StatusBonusType.DefBuf,
        secval: [6.4, 11.3, 16.4, 19.0, 21.6, 24.1, 26.7, 29.3],
    },
    HarbingerDawn: {
        name: "黎明の神剣",
        star: 3,
        atk: WEAPON_ATK3[39],
        second: CriticalBonusType.Damage,
        secval: WEAPON_SUB3.cri_dmg,
        passive: { items: CriticalBonusType.Rate, value: [14, 17.5, 21, 24.5, 28], limit: "HP90%以上の時" },
    },
    CoolSteel: {
        name: "冷刃",
        star: 3,
        atk: WEAPON_ATK3[39],
        second: StatusBonusType.AtkBuf,
        secval: WEAPON_SUB3.atk_buf,
        passive: { items: StatusBonusType.AnyDmg, value: [12, 15, 18, 21, 24], limit: "水、氷元素の影響を受けた敵" },
    },
    DarkIronSword: {
        name: "暗鉄剣",
        star: 3,
        atk: WEAPON_ATK3[39],
        second: StatusBonusType.Elem,
        secval: [31, 54, 79, 91, 104, 116, 128, 141],
        passive: { items: StatusBonusType.AtkBuf, value: [20, 25, 30, 35, 40], limit: "過負荷、超電磁、感電または雷元素拡散が発生した時", times: 12 },
    },
};
const CLAYMORE_LIST = {
    other: {
        name: "-",
        star: 1,
        second: StatusBonusType.Other,
    },
    WolfsGravestone: {
        name: "狼の末路",
        star: 5,
        atk: WEAPON_ATK5[46],
        second: StatusBonusType.AtkBuf,
        secval: WEAPON_SUB5.atk_buf,
        passive: [
            { items: StatusBonusType.AtkBuf, value: [20, 25, 30, 35, 40] },
            { items: StatusBonusType.AtkBuf, value: [40, 50, 60, 70, 80], limit: "HP30%以下の敵に命中した時", times: 12, target: BonusTarget.All },
        ],
    },
    SkywardPride: {
        name: "天空の傲",
        star: 5,
        atk: WEAPON_ATK5[48],
        second: StatusBonusType.EnRec,
        secval: [8.0, 14.1, 20.6, 23.8, 27.1, 30.3, 33.5, 36.8],
        passive: { items: StatusBonusType.AnyDmg, value: [8, 10, 12, 14, 16] },
    },
    TheUnforged: {
        name: "無工の剣",
        star: 5,
        atk: WEAPON_ATK5[46],
        second: StatusBonusType.AtkBuf,
        secval: WEAPON_SUB5.atk_buf,
        passive: [
            { items: StatusBonusType.AtkBuf, value: [4, 5, 6, 7, 8], limit: "攻撃が命中した時", times: 8, stack: 5 },
            { items: StatusBonusType.AtkBuf, value: [4, 5, 6, 7, 8], limit: "さらにシールド状態の時", times: 8, stack: 5 },
        ]
    },
    FavoniusGreatsword: {
        name: "西風大剣",
        star: 4,
        atk: WEAPON_ATK4[41],
        second: StatusBonusType.EnRec,
        secval: WEAPON_SUB4.en_rec,
    },
    SacrificialGreatsword: {
        name: "祭礼の大剣",
        star: 4,
        atk: WEAPON_ATK4[44],
        second: StatusBonusType.EnRec,
        secval: [6.7, 11.8, 17.2, 19.9, 22.6, 25.2, 27.9, 30.6],
    },
    Rainslasher: {
        name: "雨裁",
        star: 4,
        atk: WEAPON_ATK4[42],
        second: StatusBonusType.Elem,
        secval: WEAPON_SUB4.elem,
        passive: { items: StatusBonusType.AnyDmg, value: [20, 24, 28, 32, 36], limit: "水、雷元素の影響を受けた敵" },
    },
    TheBell: {
        name: "鐘の剣",
        star: 4,
        atk: WEAPON_ATK4[42],
        second: StatusBonusType.HpBuf,
        secval: WEAPON_SUB4.hp_buf,
        passive: { items: StatusBonusType.AnyDmg, value: [12, 15, 18, 21, 24], limit: "シールドが存在する時" },
    },
    LithicBlade: {
        name: "千岩古剣",
        star: 4,
        atk: WEAPON_ATK4[42],
        second: StatusBonusType.AtkBuf,
        secval: WEAPON_SUB4.atk_buf,
        passive: [
            { items: StatusBonusType.AtkBuf, value: [7, 8, 9, 10, 11], limit: "チームに璃月出身のキャラクターが1人いる毎", stack: 4 },
            { items: CriticalBonusType.Rate, value: [3, 4, 5, 6, 7], limit: "チームに璃月出身のキャラクターが1人いる毎", stack: 4 },
        ]
    },
    RoyalGreatsword: {
        name: "旧貴族大剣",
        star: 4,
        atk: WEAPON_ATK4[44],
        second: StatusBonusType.AtkBuf,
        secval: [6.0, 10.6, 15.5, 17.9, 20.3, 22.7, 25.1, 27.6],
        passive: { items: CriticalBonusType.Rate, value: [8, 10, 12, 14, 16], limit: "ダメージを与えた時", stack: 5 },
    },
    BlackcliffSlasher: {
        name: "黒岩の斬刀",
        star: 4,
        atk: WEAPON_ATK4[42],
        second: CriticalBonusType.Damage,
        secval: WEAPON_SUB4.cri_dmg,
        passive: { items: StatusBonusType.AtkBuf, value: [12, 15, 18, 21, 24], limit: "敵を倒した後", times: 30, stack: 3 },
    },
    PrototypeAminus: {
        name: "古華・試作",
        star: 4,
        atk: WEAPON_ATK4[44],
        second: StatusBonusType.AtkBuf,
        secval: [6.0, 10.6, 15.5, 17.9, 20.3, 22.7, 25.1, 27.6],
    },
    Whiteblind: {
        name: "白影の剣",
        star: 4,
        atk: WEAPON_ATK4[42],
        second: StatusBonusType.DefBuf,
        secval: WEAPON_SUB4.def_buf,
        passive: { items: [StatusBonusType.AtkBuf, StatusBonusType.DefBuf], value: [6, 7.5, 9, 10.5, 12], limit: "通常攻撃か重撃が命中した時", times: 6, stack: 4 },
    },
    SerpentSpine: {
        name: "螭龍の剣",
        star: 4,
        atk: WEAPON_ATK4[42],
        second: CriticalBonusType.Rate,
        secval: WEAPON_SUB4.cri_rate,
        passive: { items: StatusBonusType.AnyDmg, value: [6, 7, 8, 9, 10], limit: "フィールドにいる時4秒毎", stack: 5 },
    },
    SnowTombedStarsilver: {
        name: "雪葬の星銀",
        star: 4,
        atk: WEAPON_ATK4[44],
        second: ElementBonusType.Phys,
        secval: WEAPON_SUB4.phys_dmg,
    },
    SkyriderGreatsword: {
        name: "飛天大御剣",
        star: 3,
        atk: WEAPON_ATK3[39],
        second: ElementBonusType.Phys,
        secval: WEAPON_SUB3.phys_dmg,
        passive: { items: StatusBonusType.AtkBuf, value: [6, 7, 8, 9, 10], limit: "通常攻撃か重撃が命中した時", times: 6, stack: 4 },
    },
    DebateClub: {
        name: "理屈責め",
        star: 3,
        atk: WEAPON_ATK3[39],
        second: StatusBonusType.AtkBuf,
        secval: WEAPON_SUB3.atk_buf,
    },
    WhiteGreatsword: {
        name: "白鉄の大剣",
        star: 3,
        atk: WEAPON_ATK3[39],
        second: StatusBonusType.DefBuf,
        secval: WEAPON_SUB3.def_buf,
    },
    BloodtaintedGreatsword: {
        name: "龍血を浴びた剣",
        star: 3,
        atk: WEAPON_ATK3[38],
        second: StatusBonusType.Elem,
        secval: [41, 72, 105, 122, 138, 154, 171, 187],
        passive: { items: StatusBonusType.AnyDmg, value: [12, 15, 18, 21, 24], limit: "炎、雷元素の影響を受けた敵" },
    },
    FerrousShadow: {
        name: "鉄影段平",
        star: 3,
        atk: WEAPON_ATK3[39],
        second: StatusBonusType.HpBuf,
        secval: WEAPON_SUB3.hp_buf,
        passive: { items: CombatBonusType.Heavy, value: [30, 35, 40, 45, 50], limit: "HPが一定値以下の時" },
    },
};
const POLEARM_LIST = {
    other: {
        name: "-",
        star: 1,
        second: StatusBonusType.Other,
    },
    PrimordialSpear: {
        name: "和璞鳶",
        star: 5,
        atk: WEAPON_ATK5[48],
        second: CriticalBonusType.Rate,
        secval: WEAPON_SUB5.cri_rate,
        passive: [
            { items: StatusBonusType.AtkBuf, value: [3.2, 3.9, 4.6, 5.3, 6.0], limit: "敵に命中した時", times: 6, stack: 7 },
            { items: StatusBonusType.AnyDmg, value: [12, 15, 18, 21, 24], limit: "さらに7重まで発動した時" },
        ],
    },
    SkywardSpine: {
        name: "天空の脊",
        star: 5,
        atk: WEAPON_ATK5[48],
        second: StatusBonusType.EnRec,
        secval: [8.0, 14.1, 20.6, 23.8, 27.1, 30.3, 33.5, 36.8],
        passive: { items: CriticalBonusType.Rate, value: [8, 10, 12, 14, 16] },
    },
    VortexVanquisher: {
        name: "破天の槍",
        star: 5,
        atk: WEAPON_ATK5[46],
        second: StatusBonusType.AtkBuf,
        secval: WEAPON_SUB5.atk_buf,
        passive: [
            { items: StatusBonusType.AtkBuf, value: [4, 5, 6, 7, 8], limit: "攻撃が命中した時", times: 8, stack: 5 },
            { items: StatusBonusType.AtkBuf, value: [4, 5, 6, 7, 8], limit: "さらにシールド状態の時", times: 8, stack: 5 },
        ]
    },
    StaffHoma: {
        name: "護摩の杖",
        star: 5,
        atk: WEAPON_ATK5[46],
        second: CriticalBonusType.Damage,
        secval: WEAPON_SUB5.cri_dmg,
        passive: [
            { items: StatusBonusType.HpBuf, value: [20, 25, 30, 35, 40] },
            { extra: ExtraBonusType.Flat, dest: FlatBonusDest.Atk, base: FlatBonusBase.Hp, value: [0.8, 1.0, 1.2, 1.4, 1.6] },
            { extra: ExtraBonusType.Flat, dest: FlatBonusDest.Atk, base: FlatBonusBase.Hp, value: [1.0, 1.2, 1.4, 1.6, 1.8], limit: "HPが50未満の時" },
        ]
    },
    FavoniusLance: {
        name: "西風長槍",
        star: 4,
        atk: WEAPON_ATK4[44],
        second: StatusBonusType.EnRec,
        secval: [6.7, 11.8, 17.2, 19.9, 22.6, 25.2, 27.9, 30.6],
    },
    DragonsBane: {
        name: "匣中滅龍",
        star: 4,
        atk: WEAPON_ATK4[41],
        second: StatusBonusType.Elem,
        secval: [48, 85, 124, 143, 162, 182, 201, 221],
        passive: { items: StatusBonusType.AnyDmg, value: [20, 24, 28, 32, 36], limit: "水、炎元素の影響を受けた敵" },
    },
    LithicSpear: {
        name: "千岩長槍",
        star: 4,
        atk: WEAPON_ATK4[44],
        second: StatusBonusType.AtkBuf,
        secval: [6.0, 10.6, 15.5, 17.9, 20.3, 22.7, 25.1, 27.6],
        passive: [
            { items: StatusBonusType.AtkBuf, value: [7, 8, 9, 10, 11], limit: "チームに璃月出身のキャラクターが1人いる毎", stack: 4 },
            { items: CriticalBonusType.Rate, value: [3, 4, 5, 6, 7], limit: "チームに璃月出身のキャラクターが1人いる毎", stack: 4 },
        ]
    },
    RoyalSpear: {
        name: "旧貴族猟槍",
        star: 4,
        atk: WEAPON_ATK4[44],
        second: StatusBonusType.AtkBuf,
        secval: [6.0, 10.6, 15.5, 17.9, 20.3, 22.7, 25.1, 27.6],
        passive: { items: CriticalBonusType.Rate, value: [8, 10, 12, 14, 16], limit: "敵にダメージを与えた時", stack: 5 },
    },
    BlackcliffPole: {
        name: "黒岩の突槍",
        star: 4,
        atk: WEAPON_ATK4[42],
        second: CriticalBonusType.Damage,
        secval: WEAPON_SUB4.cri_dmg,
        passive: { items: StatusBonusType.AtkBuf, value: [12, 15, 18, 21, 24], limit: "敵を倒した後", times: 30, stack: 3 },
    },
    PrototypeGrudge: {
        name: "星鎌・試作",
        star: 4,
        atk: WEAPON_ATK4[42],
        second: StatusBonusType.EnRec,
        secval: [10.0, 17.7, 25.8, 29.8, 33.8, 37.9, 41.9, 45.9],
        passive: { items: [CombatBonusType.Normal, CombatBonusType.Heavy], value: [8, 10, 12, 14, 16], limit: "元素スキル発動後", times: 12, stack: 2 },
    },
    CrescentPike: {
        name: "流月の針",
        star: 4,
        atk: WEAPON_ATK4[44],
        second: ElementBonusType.Phys,
        secval: WEAPON_SUB4.phys_dmg,
    },
    Deathmatch: {
        name: "死闘の槍",
        star: 4,
        atk: WEAPON_ATK4[41],
        second: CriticalBonusType.Rate,
        secval: [8.0, 14.1, 20.6, 23.8, 27.1, 30.3, 33.5, 36.8],
        passive: [
            { items: [StatusBonusType.AtkBuf, StatusBonusType.DefBuf], value: [16, 20, 24, 28, 32], limit: "近くに敵が2人以上いる時" },
            { items: StatusBonusType.AtkBuf, value: [24, 30, 36, 42, 48], limit: "近くに敵が2人未満の時" },
        ],
    },
    DragonspineSpear: {
        name: "ドラゴンスピア",
        star: 4,
        atk: WEAPON_ATK4[41],
        second: ElementBonusType.Phys,
        secval: [15.0, 26.5, 38.7, 44.7, 50.8, 56.8, 62.9, 69.0],
    },
    BlackTassel: {
        name: "黒纓槍",
        star: 3,
        atk: WEAPON_ATK3[38],
        second: StatusBonusType.HpBuf,
        secval: [10.2, 18.0, 26.3, 30.4, 34.6, 38.7, 42.8, 46.9],
        passive: { items: StatusBonusType.AnyDmg, value: [40, 50, 60, 70, 80], limit: "スライムタイプの敵" },
    },
    Halberd: {
        name: "鉾槍",
        star: 3,
        atk: WEAPON_ATK3[40],
        second: StatusBonusType.AtkBuf,
        secval: [5.1, 9.0, 13.1, 15.2, 17.3, 19.3, 21.4, 23.5]
    },
    WhiteTassel: {
        name: "白纓槍",
        star: 3,
        atk: WEAPON_ATK3[39],
        second: CriticalBonusType.Rate,
        secval: [5.1, 9.0, 13.1, 15.2, 17.3, 19.3, 21.4, 23.4],
        passive: { items: CombatBonusType.Normal, value: [24, 30, 36, 42, 48] },
    },
};
const BOW_LIST = {
    other: {
        name: "-",
        star: 1,
        second: StatusBonusType.Other,
    },
    AmosBow: {
        name: "アモスの弓",
        star: 5,
        atk: WEAPON_ATK5[46],
        second: StatusBonusType.AtkBuf,
        secval: WEAPON_SUB5.atk_buf,
        passive: [
            { items: [CombatBonusType.Normal, CombatBonusType.Heavy], value: [12, 15, 18, 21, 24] },
            { items: [CombatBonusType.Normal, CombatBonusType.Heavy], value: [8, 10, 12, 14, 16], limit: "矢を放った後0.1秒毎", stack: 5 },
        ]
    },
    SkywardHarp: {
        name: "天空の翼",
        star: 5,
        atk: WEAPON_ATK5[48],
        second: CriticalBonusType.Rate,
        secval: [4.8, 8.5, 12.4, 14.3, 16.2, 18.2, 20.1, 22.1],
        passive: { items: CriticalBonusType.Damage, value: [20, 25, 30, 35, 40] },
    },
    ElegyForTheEnd: {
        name: "終焉を嘆く詩",
        star: 5,
        atk: WEAPON_ATK5[46],
        second: StatusBonusType.EnRec,
        secval: WEAPON_SUB5.en_rec,
        passive: [
            { items: StatusBonusType.Elem, value: [60, 75, 90, 105, 120] },
            { items: StatusBonusType.Elem, value: [100, 125, 150, 175, 200], limit: "元素スキルまたは元素爆発が4回敵に命中した時", times: 12 },
            { items: StatusBonusType.AtkBuf, value: [20, 25, 30, 35, 40], limit: "元素スキルまたは元素爆発が4回敵に命中した時", times: 12 },
        ]
    },
    FavoniusWarbow: {
        name: "西風猟弓",
        star: 4,
        atk: WEAPON_ATK4[41],
        second: StatusBonusType.EnRec,
        secval: WEAPON_SUB4.en_rec,
    },
    SacrificialBow: {
        name: "祭礼の弓",
        star: 4,
        atk: WEAPON_ATK4[44],
        second: StatusBonusType.EnRec,
        secval: [6.7, 11.8, 17.2, 19.9, 22.6, 25.2, 27.9, 30.6],
    },
    Rust: {
        name: "弓蔵",
        star: 4,
        atk: WEAPON_ATK4[42],
        second: StatusBonusType.AtkBuf,
        secval: WEAPON_SUB4.atk_buf,
        passive: [
            { items: CombatBonusType.Normal, value: [40, 50, 60, 70, 80] },
            { items: CombatBonusType.Heavy, value: [-10, -10, -10, -10, -10] },
        ],
    },
    Stringless: {
        name: "絶弦",
        star: 4,
        atk: WEAPON_ATK4[42],
        second: StatusBonusType.Elem,
        secval: WEAPON_SUB4.elem,
        passive: { items: [CombatBonusType.Skill, CombatBonusType.Burst], value: [24, 30, 36, 42, 48] },
    },
    RoyalBow: {
        name: "旧貴族長弓",
        star: 4,
        atk: WEAPON_ATK4[42],
        second: StatusBonusType.AtkBuf,
        secval: WEAPON_SUB4.atk_buf,
        passive: { items: CriticalBonusType.Rate, value: [8, 10, 12, 14, 16], limit: "敵にダメージを与えた時", stack: 5 },
    },
    BlackcliffWarbow: {
        name: "黒岩の戦弓",
        star: 4,
        atk: WEAPON_ATK4[44],
        second: CriticalBonusType.Damage,
        secval: [8.0, 14.1, 20.6, 23.8, 27.1, 30.3, 33.5, 36.8],
        passive: { items: StatusBonusType.AtkBuf, value: [12, 15, 18, 21, 24], limit: "敵を倒した後", times: 30, stack: 3 },
    },
    PrototypeCrescent: {
        name: "澹月・試作",
        star: 4,
        atk: WEAPON_ATK4[42],
        second: StatusBonusType.AtkBuf,
        secval: WEAPON_SUB4.atk_buf,
        passive: { items: StatusBonusType.AtkBuf, value: [36, 45, 54, 63, 72], limit: "狙い撃ちが弱点に命中した時", times: 10 },
    },
    CompoundBow: {
        name: "リングボウ",
        star: 4,
        atk: WEAPON_ATK4[41],
        second: ElementBonusType.Phys,
        secval: [15.0, 26.5, 38.7, 44.7, 50.8, 56.8, 62.9, 69.0],
        passive: { items: StatusBonusType.AtkBuf, value: [4, 5, 6, 7, 8], limit: "通常攻撃と狙い撃ちが命中した時", times: 6, stack: 4 },
    },
    ViridescentHunt: {
        name: "蒼翠の狩猟弓",
        star: 4,
        atk: WEAPON_ATK4[42],
        second: CriticalBonusType.Rate,
        secval: WEAPON_SUB4.cri_rate,
    },
    WindblumeOde: {
        name: "風花の頌歌",
        star: 4,
        atk: WEAPON_ATK4[42],
        second: StatusBonusType.Elem,
        secval: WEAPON_SUB4.elem,
        passive: { items: StatusBonusType.AtkBuf, value: [16, 20, 24, 28, 32], limit: "元素スキルを発動した後", times: 6 },
    },
    SharpshootersOath: {
        name: "シャープシューターの誓い",
        star: 3,
        atk: WEAPON_ATK3[39],
        second: CriticalBonusType.Damage,
        secval: WEAPON_SUB3.cri_dmg,
        passive: { items: StatusBonusType.AnyDmg, value: [24, 30, 36, 42, 48], limit: "弱点" },
    },
    RavenBow: {
        name: "鴉羽の弓",
        star: 3,
        atk: WEAPON_ATK3[40],
        second: StatusBonusType.Elem,
        secval: [20, 36, 53, 61, 69, 77, 85, 94],
        passive: { items: StatusBonusType.AnyDmg, value: [12, 15, 18, 21, 24], limit: "水、炎元素の影響を受けた敵" },
    },
    Slingshot: {
        name: "弾弓",
        star: 3,
        atk: WEAPON_ATK3[38],
        second: CriticalBonusType.Rate,
        secval: [6.8, 12.0, 17.5, 20.3, 23.0, 25.7, 28.5, 31.2],
        passive: [
            { items: [CombatBonusType.Normal, CombatBonusType.Heavy], value: [36, 42, 48, 54, 60], limit: "矢が発射後0.3秒以内に敵に命中した時" },
            { items: [CombatBonusType.Normal, CombatBonusType.Heavy], value: [-10, -10, -10, -10, -10], limit: "矢が発射後0.3秒より長く敵に命中した時" }
        ]
    },
    Messenger: {
        name: "文使い",
        star: 3,
        atk: WEAPON_ATK3[40],
        second: CriticalBonusType.Damage,
        secval: [6.8, 12.0, 17.5, 20.3, 23.0, 25.7, 28.5, 31.2],
    },
    RecurveBow: {
        name: "リカーブボウ",
        star: 3,
        atk: WEAPON_ATK3[38],
        second: StatusBonusType.HpBuf,
        secval: [10.2, 18.0, 26.3, 30.4, 34.6, 38.7, 42.8, 46.9],
    },
};
const CATALYST_LIST = {
    other: {
        name: "-",
        star: 1,
        second: StatusBonusType.Other,
    },
    SkywardAtlas: {
        name: "天空の巻",
        star: 5,
        atk: WEAPON_ATK5[48],
        second: StatusBonusType.AtkBuf,
        secval: [7.2, 12.7, 18.5, 21.4, 24.4, 27.3, 30.2, 33.1],
        passive: { items: ElementBonusType.Any, value: [12, 15, 18, 21, 24] },
    },
    LostSacredWinds: {
        name: "四風原典",
        star: 5,
        atk: WEAPON_ATK5[46],
        second: CriticalBonusType.Rate,
        secval: [7.2, 12.7, 18.5, 21.4, 24.4, 27.3, 30.2, 33.1],
        passive: { items: ElementBonusType.Any, value: [8, 10, 12, 14, 16], limit: "出場中は4秒毎", stack: 4 },
    },
    MemoryDust: {
        name: "浮世の錠",
        star: 5,
        atk: WEAPON_ATK5[46],
        second: StatusBonusType.AtkBuf,
        secval: WEAPON_SUB5.atk_buf,
        passive: [
            { items: StatusBonusType.AtkBuf, value: [4, 5, 6, 7, 8], limit: "攻撃が命中した時", times: 8, stack: 5 },
            { items: StatusBonusType.AtkBuf, value: [4, 5, 6, 7, 8], limit: "さらにシールド状態の時", times: 8, stack: 5 },
        ]
    },
    FavoniusCodex: {
        name: "西風秘典",
        star: 4,
        atk: WEAPON_ATK4[42],
        second: StatusBonusType.EnRec,
        secval: [10.0, 17.7, 25.8, 29.8, 33.8, 37.9, 41.9, 45.9],
    },
    SacrificialFragments: {
        name: "祭礼の断片",
        star: 4,
        atk: WEAPON_ATK4[41],
        second: StatusBonusType.Elem,
        secval: [48, 85, 124, 143, 162, 182, 201, 221],
    },
    EyePerception: {
        name: "昭心",
        star: 4,
        atk: WEAPON_ATK4[41],
        second: StatusBonusType.AtkBuf,
        secval: [12.0, 21.2, 30.9, 35.7, 40.6, 45.4, 50.3, 55.1],
    },
    TheWidsith: {
        name: "流浪楽章",
        star: 4,
        atk: WEAPON_ATK4[42],
        second: CriticalBonusType.Damage,
        secval: WEAPON_SUB4.cri_dmg,
        passive: [
            { items: StatusBonusType.AtkBuf, value: [60, 75, 90, 105, 120], limit: "叙唱：キャラ登場時", times: 10 },
            { items: ElementBonusType.Any, value: [48, 60, 72, 84, 96], limit: "詠唱：キャラ登場時", times: 10 },
            { items: StatusBonusType.Elem, value: [240, 300, 360, 420, 480], limit: "間奏曲：キャラ登場時", times: 10 },
        ],
    },
    WineAndSong: {
        name: "ダークアレイの酒と詩",
        star: 4,
        atk: WEAPON_ATK4[44],
        second: StatusBonusType.EnRec,
        secval: [6.7, 11.8, 17.2, 19.9, 22.6, 25.2, 27.9, 30.6],
        passive: { items: StatusBonusType.AtkBuf, value: [25, 30, 35, 40, 45], limit: "ダッシュまたはダッシュを代替する能力を使用した時", times: 5 },
    },
    RoyalGrimoire: {
        name: "旧貴族秘法録",
        star: 4,
        atk: WEAPON_ATK4[44],
        second: StatusBonusType.AtkBuf,
        secval: [6.0, 10.6, 15.5, 17.9, 20.3, 22.7, 25.1, 27.6],
        passive: { items: CriticalBonusType.Rate, value: [8, 10, 12, 14, 16], limit: "ダメージを与えた時", stack: 6 },
    },
    BlackcliffAmulet: {
        name: "黒岩の緋玉",
        star: 4,
        atk: WEAPON_ATK4[42],
        second: CriticalBonusType.Damage,
        secval: WEAPON_SUB4.cri_dmg,
        passive: { items: StatusBonusType.AtkBuf, value: [12, 15, 18, 21, 24], limit: "敵を倒した後", times: 30, stack: 3 },
    },
    PrototypeMalice: {
        name: "金珀・試作",
        star: 4,
        atk: WEAPON_ATK4[42],
        second: StatusBonusType.HpBuf,
        secval: WEAPON_SUB4.hp_buf,
    },
    MappaMare: {
        name: "万国諸海の図譜",
        star: 4,
        atk: WEAPON_ATK4[44],
        second: StatusBonusType.Elem,
        secval: [24, 42, 62, 71, 81, 91, 101, 110],
        passive: { items: ElementBonusType.Any, value: [8, 10, 12, 14, 16], limit: "元素反応を起こした後", times: 10, stack: 2 },
    },
    SolarPearl: {
        name: "匣中日月",
        star: 4,
        atk: WEAPON_ATK4[42],
        second: CriticalBonusType.Rate,
        secval: WEAPON_SUB4.cri_rate,
        passive: [
            { items: [CombatBonusType.Skill, CombatBonusType.Burst], value: [20, 25, 30, 35, 40], limit: "通常攻撃が命中した時", times: 6 },
            { items: CombatBonusType.Normal, value: [20, 25, 30, 35, 40], limit: "元素スキルか元素爆発が命中した時", times: 6 },
        ],
    },
    Frostbearer: {
        name: "冬忍びの実",
        star: 4,
        atk: WEAPON_ATK4[42],
        second: StatusBonusType.AtkBuf,
        secval: WEAPON_SUB4.atk_buf,
    },
    AmberCatalyst: {
        name: "翡玉法珠",
        star: 3,
        atk: WEAPON_ATK3[40],
        second: StatusBonusType.Elem,
        secval: [20, 36, 53, 61, 69, 77, 85, 94],
        passive: { items: StatusBonusType.AtkBuf, value: [20, 25, 30, 35, 40], limit: "蒸発、感電、凍結、または水元素拡散反応後", times: 12 },
    },
    MagicGuide: {
        name: "魔導緒論",
        star: 3,
        atk: WEAPON_ATK3[38],
        second: StatusBonusType.Elem,
        secval: [41, 72, 105, 122, 138, 154, 171, 187],
        passive: { items: StatusBonusType.AnyDmg, value: [12, 15, 18, 21, 24], limit: "水、雷元素の影響を受けた敵" },
    },
    TalesDragonSlayers: {
        name: "竜殺しの英傑譚",
        star: 3,
        atk: WEAPON_ATK3[39],
        second: StatusBonusType.HpBuf,
        secval: WEAPON_SUB3.hp_buf,
        passive: { items: StatusBonusType.AtkBuf, value: [24, 30, 36, 42, 48], limit: "次に登場するキャラ", times: 10, target: BonusTarget.Next },
    },
    OtherworldlyStory: {
        name: "異世界旅行記",
        star: 3,
        atk: WEAPON_ATK3[39],
        second: StatusBonusType.EnRec,
        secval: [8.5, 15.0, 21.9, 25.3, 28.8, 32.2, 35.6, 39.0],
    },
    TwinNephrite: {
        name: "特級の宝玉",
        star: 3,
        atk: WEAPON_ATK3[40],
        second: CriticalBonusType.Rate,
        secval: [3.4, 6.0, 8.8, 10.1, 11.5, 12.9, 14.2, 15.6],
        passive: { items: StatusBonusType.AtkBuf, value: [12, 14, 16, 18, 20], limit: "敵を倒した後", times: 15 },
    },
};
const WEAPON_LIST = {
    sword: SWORD_LIST,
    claymore: CLAYMORE_LIST,
    polearm: POLEARM_LIST,
    bow: BOW_LIST,
    catalyst: CATALYST_LIST
};
